image: gcc

build:
  stage: build
  before_script: 
    - echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main" >> /etc/apt/sources.list
    - echo "deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main" >> /etc/apt/sources.list
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - apt update && apt -y install make cmake git wget llvm-5.0-dev
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
     - build/

test:
  stage: test
  before_script: 
    - echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main" >> /etc/apt/sources.list
    - echo "deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main" >> /etc/apt/sources.list
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - apt update && apt -y install make cmake git wget llvm-5.0-dev
  script:
    - cd build
    - make runtests
    - make runmoretests
  artifacts:
    paths:
     - build/check/
