image: gcc

build:
  stage: build
  before_script: 
    - apt update && apt -y install make cmake llvm-5.0-dev
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
     - build/

test:
  stage: test
  before_script: 
    - apt update && apt -y install make cmake llvm-5.0-dev
  script:
    - cd build
    - make runtests
    - make runmoretests
  artifacts:
    paths:
     - build/check/
